name: "Close Stale Issues"

# Controls when the action will run.
on:
  schedule:
  - cron: "0 6 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - uses: aws-actions/stale-issue-cleanup@7de35968489e4142233d2a6812519a82e68b5c38 # v6
      with:
        # Setting messages to an empty string will cause the automation to skip
        # that category
        ancient-issue-message: This issue has not received any attention in 2 years. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-issue-message: This issue has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-pr-message: This PR has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        
        # These labels are required
        stale-issue-label: closing-soon
        exempt-issue-label: no-autoclose
        stale-pr-label: closing-soon
        exempt-pr-label: no-autoclose
        response-requested-label: response-requested

        # Don't set closed-for-staleness label to skip closing very old issues
        # regardless of label
        closed-for-staleness-label: closed-for-staleness

        # Issue timing
        days-before-stale: 2
        days-before-close: 5
        days-before-ancient: 730

        # If you don't want to mark a issue as being ancient based on a
        # threshold of "upvotes", you can set this here. An "upvote" is
        # the total number of +1, heart, hooray, and rocket reactions
        # on an issue.
        minimum-upvotes-to-exempt: 5

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # loglevel: DEBUG
        # Set dry-run to true to not perform label or close actions.
        dry-run: false